### ISSUE TITLE
Bug: Can't save config changes (host address) in the UI without accepting contracts

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#113] opened 2023-07-14 20:29 UTC
### Current Behavior

Bug: Can't save config changes in the UI without accepting contracts

### Expected Behavior

You should be able to save config (specifically the host address) settings without enabling contracts.  

### Version

0.1.0 Beta

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment] 2023-07-14 21:01
duplicate of #101

**Closed by n8maninger** 2023-07-14 21:01 UTC
Labels: bug
