### ISSUE TITLE
Last bucket on cumulative graphs need to be dropped

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/hostd#425] opened 2024-07-01 17:03 UTC
### Current Behavior

The Bandwidth and Operations graph show cumulative data but the last period is always the current one and so has incomplete data. See the attached graph with an image of the month's data. The graph drops at the end as it is for today which is incomplete, but this leaves you thinking today's bandwidth is less that yesterday's, whereas, in reality it is going to beat yesterday's if it continues like this.

### Expected Behavior

I think the solution is to drop the last bucket, or in the last bucket have both an actual figure and an extrapolated figure, but the extrapolation would need to be very clear that it is extrapolated.

### Version

v1.1.0

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 24.04 LTS

**Comment by AZComputerSolutions** [comment] 2024-07-19 16:26
This was already reported quite some time ago.

https://github.com/SiaFoundation/hostd/issues/276

**Comment by n8maninger** [comment] 2024-07-19 17:06
Closing as duplicate of #276

**Closed by n8maninger** 2024-07-19 17:06 UTC
Labels: bug
