### ISSUE TITLE
update the wallet icon in hostd to have the option of displaying sc and fait currency (ie: CAD if currently selected)

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#97] opened 2023-07-01 18:17 UTC
### Description

<img width="65" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/7236f206-0f79-4e14-bbba-624461f4455f">
Right now it looks like above.

<img width="135" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/31a3fc53-8b73-4b9f-acc1-5df6604733e7">
Similar to the above icon.

### Version

0.1.0 Beta

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by rdwild** [comment] 2023-07-01 18:18
It might be a bit picky but KS means nothing to me.  However SC or CAD means soemthing.

**Comment by n8maninger** [comment] 2023-08-09 23:38
Duplicate of #123

**Closed by n8maninger** 2023-08-09 23:38 UTC
Labels: feature
