### ISSUE TITLE
Hostd - contracts page (page no resizing very well)

### ISSUE THREAD

**Issue by rdwild** [SiaFoundation/hostd#73] opened 2023-06-10 15:38 UTC
### Current Behavior

There is too much blank space between columns and at the same time it is not showing the full contract address when there is more than enough space on the screen for it.

<img width="1904" alt="image" src="https://github.com/SiaFoundation/hostd/assets/44580802/8c7d8707-7d80-4126-b120-dc0895d9a852">

### Expected Behavior

It would be nice if there was an option to add more columns of data (not sure what at this point but I would suggest looking to host manager as a guide) and has full display of the contract id.  

### Version

0.1.0 Alpha 3

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment] 2023-06-10 15:55
This seems like a duplicate of #52

**Closed by n8maninger** 2023-06-10 15:55 UTC
Labels: bug

**Comment by rdwild** [comment] 2023-07-16 01:08
Actually its not, one is to much space the other is a field getting cut off.
