### ISSUE TITLE
The copy to clipboard function seems to be broken in 1.0.0

### ISSUE THREAD

**Issue by AZComputerSolutions** [SiaFoundation/hostd#258] opened 2023-12-30 23:16 UTC
### Current Behavior

It was working but now when you select to copy an address (this is both Renterd and hosted) it says that it copied the address but when you go to paste it there is nothing pasted.

### Expected Behavior

copy address, copies the requested address into the clipboard.

### Steps to Reproduce

I have tried this on 1.0.0 renterd and hosted.

go to the sia icon above and wait for address to pop up, click on the dropdown and select copy.  it pops up and says that it copied to the clipboard but when you go to paste nothing shows up.

### Version

1.0.0

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, windows 10 chrome.

**Comment by n8maninger** [comment] 2023-12-31 01:16
Duplicate of #247

**Closed by n8maninger** 2023-12-31 01:16 UTC
Labels: bug
